apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: kind-kind
spec:
  request: $(cat kind-kind.csr | base64 | tr -d '\n')
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - client auth
