name: Test Connectivity

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-connectivity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        kubectl config set-cluster kind-kind --server=https://8363-58-65-202-78.ngrok-free.app --insecure-skip-tls-verify=true
        kubectl config set-context kind-kind --cluster=kind-kind
        kubectl config use-context kind-kind

    - name: Test kubectl connectivity
      run: |
        kubectl get nodes
