on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-connectivity:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: |
        kubectl config set-cluster kind-kind --server=https://aaaa-58-65-202-78.ngrok-free.app --insecure-skip-tls-verify=true
        kubectl config set-credentials github-actions --token=${{ secrets.KUBE_TOKEN }}
        kubectl config set-context kind-kind --cluster=kind-kind --user=github-actions
        kubectl config use-context kind-kind

    - name: Test kubectl connectivity
      run: |
        kubectl get nodes --insecure-skip-tls-verify=true --request-timeout=30s --v=5

    - name: Debug kubectl config
      run: |
        kubectl config view
        kubectl config current-context

    - name: Check API server health
      run: |
        curl -k https://aaaa-58-65-202-78.ngrok-free.app/healthz