name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t flask-app:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: |
          docker tag flask-app:latest muhammad679/flask-app:latest
          docker push muhammad679/flask-app:latest
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Load Docker image into kind cluster
        run: kind load docker-image flask-app:latest --name kind --loglevel debug

      - name: Deploy to Blue namespace
        run: |
          kubectl apply -f blue-deployment.yaml
          kubectl apply -f blue-service.yaml
          kubectl rollout status deployment/flask-app -n blue

      - name: Health check Blue
        run: |
          kubectl run health-check --rm -i --tty --image=appropriate/curl -- curl -f http://flask-app.blue.s