name: Connectivity Test

on:
  push:
    branches:
      - main

jobs:
  test-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}

      - name: Set KUBECONFIG
        run: export KUBECONFIG=~/.kube/config

      - name: Debug kubeconfig
        run: |
          kubectl config get-contexts
          cat ~/.kube/config

      - name: Switch to correct context
        run: kubectl config use-context kind-kind

      - name: Verify cluster nodes
        run: kubectl get nodes
